version: '3'

services:
    app:
        build: .
        container_name: events_app
        entrypoint: wait-for db:5432 -t 40 -- ./.docker/entrypoint.sh
        tty: true
        volumes:
            - .:/home/events/app
        ports:
            - 8000:8000
        # networks:
        #     - app-network
        depends_on:
            - db
    db:
        container_name: events_db
        build: .docker/postgresql
        tty: true
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=events
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        ports:
            - "5432:5432"
        # networks:
        #     - app-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: django-admin-pgadmin
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@user.com
            - PGADMIN_DEFAULT_PASSWORD=123456
        ports:
            - "9000:80"
        # networks:
        #     - app-network